HTTP/1.1 405 Method Not Allowed
x-rblx-origin: lb
cache-control: no-cache, no-store
content-type: text/html
connection: close

<html><body><h1>405 Method Not Allowed</h1>
Method Not Allowed <^)))<
</body></html>
