HTTP/1.1 413 Payload Too Large
x-rblx-origin: lb
cache-control: no-cache, no-store
content-type: text/html
connection: close

<html><body><h1>413 Payload Too Large</h1>
Payload Too Large <^)))<
</body></html>
