HTTP/1.1 429 Too Many Requests
x-rblx-origin: lb
cache-control: no-cache, no-store
content-type: text/html
connection: close

<html><body><h1>429 Too Many Requests</h1>
Too Many Requests <^)))<
</body></html>
